#**Introducción a Python**

## **Asignación automatica de tipos de variables**

En Python no es necesario declarar explícitamente el tipo de las variables. El intérprete trata de inferir el tipo de las variables según se usan. Igualmente, las operaciones tienen semántica distinta para distintos tipos de datos. Fíjate en el ejemplo siguiente. ¿Por qué el resultado de las dos últimas divisiones no es el mismo?

In [ ]:
a = 10
b = 3
c = 3.1
d = "hola"
print (type(a), type(b), type(c), type(d))

<class 'int'> <class 'int'> <class 'float'> <class 'str'>


Sin embargo, a partir de **Python 3.5**, *puedes usar las "Annotations" (**anotaciones**) de tipo para indicar el tipo esperado de una variable*. Aunque estas anotaciones no afectan el comportamiento real del programa, pueden ser útiles para proporcionar información sobre los tipos de variables a otros programadores o herramientas de análisis estático de código.

In [ ]:
# Para determinar la version de python usada en colab
!python --version

Python 3.10.12


In [ ]:
# Anotación de tipo en una variable
c: int = 42
d: str = "Ejemplo"
print (type(c), type(d))

<class 'int'> <class 'str'>


In [ ]:
# Anotación de tipo en una variable
a: int =4
b: int =5
resultado: int = (a+b)
print(resultado)

9


In [ ]:
#Es importante saber el tipo de dato, dado que este establece qué valores puede tomar una variable
# y qué operaciones se pueden realizar sobre la misma.
a = 10
b = 3
c = 3.1
d = "hola"
print ("a =",a,"; b =",b, "; c =",c)
print ("a/b =", a/b)
print ("a/c =", a/c)
print ("a/b =", a//b)
print ("a/c =", a//c)

a = 10 ; b = 3 ; c = 3.1
a/b = 3.3333333333333335
a/c = 3.225806451612903
a/b = 3
a/c = 3.0


#**Tipos de Datos**

## **Números enteros**
* El tipo de los números enteros es int.
* Este tipo de dato comprende el conjunto de todos los números enteros, pero como dicho conjunto es infinito, en Python el conjunto está limitado realmente por la *capacidad de la memoria disponible*. No hay un límite de representación impuesto por el lenguaje.
* Pero tranquilidad, que para el 99% de los programas que desarrolles tendrás suficiente con el subconjunto que puedes representar.

In [ ]:
a = -1          # a es de tipo int y su valor es -1
b = a + 2    # b es de tipo int y su valor es 1
print(b)

1


También podemos representar los números enteros en formato binario, octal o hexadecimal.

In [ ]:
diez = 10
diez_binario = 0b1010
diez_octal = 0o12
diez_hex = 0xa

#Al realizar la impresion los convierte a enteros si quedemos verlos en otros formato debemos usar funciones
print(diez)
print(diez_binario)
print(diez_octal)
print(diez_hex)

# Usando Funciones de conversion podemos ver otros formatos
print(bin(10))
print(oct(10))
print(hex(10))

10
10
10
10
0b1010
0o12
0xa


Fíjate cómo las siguientes expresiones son equivalentes:

In [ ]:
a=15
if a > 10:
    s = "mayor que 10"
else:
    s = "menor que 10"

print(s)

mayor que 10


In [ ]:
a = 5
s = "mayor que 10" if a > 10 else "menor que 10"
print(s)

menor que 10


##**Booleanos**

In [ ]:
# Conjunción AND

print(True and True)

print(True and False)

print(False and True)

print(False and False)
print()

# Disyunción OR

print(True or True)

print(True or False)

print(False or True)

print(False or False)


True
False
False
False

True
True
True
False


##**Cadena de Caracteres** (*string*) **STR**

In [ ]:
hola = 'Hola "Pythonista"'
hola_2 = 'Hola \'Pythonista\' '
hola_3 = "Hola 'Pythonista' "
print(hola)
print(hola_2)
print(hola_3)
type(hola_3)

Hola "Pythonista"
Hola 'Pythonista' 
Hola 'Pythonista' 


str

##**Conocer el tipo de una variable**

Para conocer el tipo de variable se tienen dos funciones para que puedas jugar con todo lo que hemos visto en este tutorial.
Son **type()** e **isinstance()**


In [ ]:
print(type(3))
print(type(2.78))
print(type('Hola'))

print(isinstance(3, float))
print(isinstance(3, int))
print(isinstance(3, bool))
print(isinstance(False, bool))

<class 'int'>
<class 'float'>
<class 'str'>
False
True
False
True


##**Conversión de tipos**
Cuando el tipo de datos es errado los podemos convertir a otro tipo mediante las siguientes funciones.

* int(x, base)
* bin(x)
* hex(x)
* oct(x)
* float(x)
* str(x)
* ord(x)
* chr()

In [ ]:
print(int("1010", 2))
print(bin(42))
print(hex(255))
print(oct(64))
print(float("3.14"))
print(str(123))
print()

caracter = 'A'
print(ord(caracter))

valor_unicode = 65
print(chr(valor_unicode))

10
0b101010
0xff
0o100
3.14
123

65
A


## **Listas**
* Otro tipo muy importante de secuencia son las listas.
* Entre las secuencias, el más versátil, es la lista, para definir una, usted debe escribir es entre corchetes, separando sus elementos con comas cada uno.


In [ ]:
factura = ['pan', 'huevos', 100, 1234]
factura

['pan', 'huevos', 100, 1234]

In [ ]:
a = [1,2,3,"hola", [10, "nunca", 90], -32]
print (a)
print (len(a))

[1, 2, 3, 'hola', [10, 'nunca', 90], -32]
6


In [ ]:
for i in range(len(a)):
    print (i, "-->", a[i])

0 --> 1
1 --> 2
2 --> 3
3 --> hola
4 --> [10, 'nunca', 90]
5 --> -32


In [ ]:
for i in a:
    print (i)

1
2
3
hola
[10, 'nunca', 90]
-32


In [ ]:
print (a[2:])
print (a[-3:])
print (a[4])

[3, 'hola', [10, 'nunca', 90], -32]
['hola', [10, 'nunca', 90], -32]
[10, 'nunca', 90]


In [ ]:
print(a[4][1])
print(a[4][1:])

nunca
['nunca', 90]


In [ ]:
print((a[3]))
print((a[3][2:]))

hola
la


In [ ]:
print (a[5])
#print (a[1][1:])

-32


In [ ]:
a = [10, -4, 20, 5]

o = ["10A", "-4B", "20A", "5A"]

o = []
for i in a:
    if i<0:
        o.append(str(i)+"B")
    else:
        o.append(str(i)+"A")

print(o)

['10A', '-4B', '20A', '5A']


In [ ]:
def convert(x):
    return str(x)+"B" if x<0 else str(x)+"A"

o = [convert(i) for i in a]
print(o)

['10A', '-4B', '20A', '5A']


In [ ]:
r = []
for i in range(10):
    r.append("el numero "+str(i))
print(r)

['el numero 0', 'el numero 1', 'el numero 2', 'el numero 3', 'el numero 4', 'el numero 5', 'el numero 6', 'el numero 7', 'el numero 8', 'el numero 9']


In [ ]:
r = ["el numero "+str(i) for i in range(10)]
print(r)

['el numero 0', 'el numero 1', 'el numero 2', 'el numero 3', 'el numero 4', 'el numero 5', 'el numero 6', 'el numero 7', 'el numero 8', 'el numero 9']


##**Tuplas**
Son objetos de tipo secuencia, específicamente es un tipo de dato lista **inmutable**. Esta no puede modificarse de ningún modo después de su creación.

In [ ]:
valores = ("Python", True, "Zope", 5)
print("True ->", valores.count(True))
print("'Zope' ->", valores.count('Zope'))
print("5 ->", valores.count(5))


True -> 1
'Zope' -> 1
5 -> 1


## **Diccionarios**

El diccionario, define una relación uno a uno entre claves y valores.

In [ ]:
import numpy as np

In [ ]:
d = {"i1": 16, "nombre": "haskel", "edad": 32}

In [ ]:
print(type(d))

<class 'dict'>


In [ ]:
print(d.items())

dict_items([('i1', 16), ('nombre', 'haskel'), ('edad', 32)])


In [ ]:
print(d.keys())

dict_keys(['i1', 'nombre', 'edad'])


In [ ]:
print(d.values())

dict_values([16, 'haskel', 32])


In [ ]:
for i in list(d.keys()):
    print("la clave", i, "tiene el valor", d[i])

la clave i1 tiene el valor 16
la clave nombre tiene el valor haskel
la clave edad tiene el valor 32


In [ ]:
print(d["nombre"])

haskel


Creacion de valores aleatorios

In [ ]:
r10 = list(range(10))
rr  = np.random.randint(10, size=10)
print(r10)
print(rr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 8 9 1 5 3 8 3 9 0]


In [ ]:
matrizAleatoria = np.random.randint(10, size=(3,4))
print(matrizAleatoria)

[[0 1 3 3]
 [7 5 3 6]
 [9 6 0 8]]


In [ ]:
matrizAleatoria[0,1]

1

In [ ]:
print(matrizAleatoria.diagonal())

[0 5 0]


In [ ]:
for i in range(len(rr)):
    print("el indice", i, "tiene el valor", rr[i])

el indice 0 tiene el valor 2
el indice 1 tiene el valor 3
el indice 2 tiene el valor 6
el indice 3 tiene el valor 8
el indice 4 tiene el valor 0
el indice 5 tiene el valor 8
el indice 6 tiene el valor 8
el indice 7 tiene el valor 6
el indice 8 tiene el valor 9
el indice 9 tiene el valor 5


Los diccionarios son listas de asociaciones entre objetos (como _hashes_ en Java)

In [ ]:
d = {"i1": 16, "nombre": "haskel", "edad": 32}
print(d)
print(list(d.keys()))
print(d["nombre"], d["edad"])
for k in list(d.keys()):
    print(d[k])

{'i1': 16, 'nombre': 'haskel', 'edad': 32}
['i1', 'nombre', 'edad']
haskel 32
16
haskel
32


In [ ]:
a=-1
b = 2.55
print(type(a))
print(type(b))
c=a+b
type(c)
c

<class 'int'>
<class 'float'>


1.5499999999999998

In [ ]:
!python --version

Python 3.10.12


In [ ]:
0b1101
z =bin(13)
a = 12
a
z

'0b1101'

funcines

In [ ]:
def sume(a,b):
  suma= a+b
  return suma

funcion landa

In [ ]:
x = lambda a, b : a + b
print(x(5, 6))

11


Mapeo de funciones

In [ ]:
def double(a):
  return a*2

mi_lista = [1,2,3,4,5]
mi_lista_doble = list(map(double, mi_lista))
print(mi_lista_doble)

[2, 4, 6, 8, 10]


In [ ]:
mi_lista = [1,2,3,4,5]
mi_lista_doble = list(map(lambda x: x*2, mi_lista))
print(mi_lista_doble)

[2, 4, 6, 8, 10]


In [ ]:
mi_lista = [18, -3, 5, 0, -1, 12]
lista_nueva = list(filter(lambda x: x > 0, mi_lista))
print(lista_nueva) # [18, 5, 12]

[18, 5, 12]


Clases


In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def greet(self):
        return f"Hello, my name is {self.name} and I am {self.age} years old."

# Uso de la clase
p1 = Person("Andres", 34)
print(p1.greet())


Hello, my name is Andres and I am 34 years old.


clases con metodos y propiedades

Herencias y propiedades

In [ ]:
class Animal:
    def __init__(self, name):
        self.name = name

    def make_sound(self):
        return "Some generic sound"

class Dog(Animal):
    def make_sound(self):
        return "Woof woof!"

# Uso de las clases
a = Animal("Unknown")
d = Dog("Buddy")
print(a.make_sound())  # Some generic sound
print(d.make_sound())  # Woof woof!
